2025-05-17 20:26:15,077 INFO    Thread-25 (_run_job):788773 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-05-17 20:26:15,077 INFO    Thread-25 (_run_job):788773 [wandb_setup.py:_flush():67] Configure stats pid to 788773
2025-05-17 20:26:15,077 INFO    Thread-25 (_run_job):788773 [wandb_setup.py:_flush():67] Loading settings from /speech/utkarsh/.config/wandb/settings
2025-05-17 20:26:15,077 INFO    Thread-25 (_run_job):788773 [wandb_setup.py:_flush():67] Loading settings from /speech/utkarsh/da6401_assignment3/wandb/settings
2025-05-17 20:26:15,077 INFO    Thread-25 (_run_job):788773 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-05-17 20:26:15,077 INFO    Thread-25 (_run_job):788773 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /speech/utkarsh/da6401_assignment3/wandb/run-20250517_202615-p9vxcfyy/logs/debug.log
2025-05-17 20:26:15,077 INFO    Thread-25 (_run_job):788773 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /speech/utkarsh/da6401_assignment3/wandb/run-20250517_202615-p9vxcfyy/logs/debug-internal.log
2025-05-17 20:26:15,078 INFO    Thread-25 (_run_job):788773 [wandb_init.py:init():781] calling init triggers
2025-05-17 20:26:15,078 INFO    Thread-25 (_run_job):788773 [wandb_init.py:init():786] wandb.init called with sweep_config: {'batch_size': 32, 'beam_size': None, 'cell_type': 'lstm', 'decoder_dropout': 0.5, 'embedding_size': 256, 'encoder_dropout': 0.5, 'hidden_size': 256, 'learning_rate': 0.0001, 'num_layers': 1}
config: {'_wandb': {}}
2025-05-17 20:26:15,078 INFO    Thread-25 (_run_job):788773 [wandb_init.py:init():809] starting backend
2025-05-17 20:26:15,078 INFO    Thread-25 (_run_job):788773 [wandb_init.py:init():813] sending inform_init request
2025-05-17 20:26:15,080 INFO    Thread-25 (_run_job):788773 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-17 20:26:15,080 INFO    Thread-25 (_run_job):788773 [wandb_init.py:init():823] backend started and connected
2025-05-17 20:26:15,081 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_config_callback():1327] config_cb None None {'batch_size': 32, 'beam_size': None, 'cell_type': 'lstm', 'decoder_dropout': 0.5, 'embedding_size': 256, 'encoder_dropout': 0.5, 'hidden_size': 256, 'learning_rate': 0.0001, 'num_layers': 1}
2025-05-17 20:26:15,083 INFO    Thread-25 (_run_job):788773 [wandb_init.py:init():915] updated telemetry
2025-05-17 20:26:15,091 INFO    Thread-25 (_run_job):788773 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-05-17 20:26:15,787 INFO    Thread-25 (_run_job):788773 [wandb_init.py:init():1014] starting run threads in backend
2025-05-17 20:26:15,976 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_console_start():2454] atexit reg
2025-05-17 20:26:15,977 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-05-17 20:26:15,977 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-05-17 20:26:15,977 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_redirect():2394] Redirects installed.
2025-05-17 20:26:15,977 INFO    Thread-25 (_run_job):788773 [wandb_init.py:init():1056] run started, returning control to user process
2025-05-17 20:26:15,980 INFO    Thread-25 (_run_job):788773 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /speech/utkarsh/da6401_assignment3/wandb/run-20250517_202615-p9vxcfyy/logs/debug.log
2025-05-17 20:26:15,980 INFO    Thread-25 (_run_job):788773 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /speech/utkarsh/da6401_assignment3/wandb/run-20250517_202615-p9vxcfyy/logs/debug.log
2025-05-17 20:26:15,980 INFO    Thread-25 (_run_job):788773 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /speech/utkarsh/da6401_assignment3/wandb/run-20250517_202615-p9vxcfyy/logs/debug-internal.log
2025-05-17 20:26:15,980 INFO    Thread-25 (_run_job):788773 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /speech/utkarsh/da6401_assignment3/wandb/run-20250517_202615-p9vxcfyy/logs/debug-internal.log
2025-05-17 20:26:15,980 INFO    Thread-25 (_run_job):788773 [wandb_init.py:init():781] calling init triggers
2025-05-17 20:26:15,980 INFO    Thread-25 (_run_job):788773 [wandb_init.py:init():781] calling init triggers
2025-05-17 20:26:15,980 INFO    Thread-25 (_run_job):788773 [wandb_init.py:init():786] wandb.init called with sweep_config: {'batch_size': 32, 'beam_size': None, 'cell_type': 'lstm', 'decoder_dropout': 0.5, 'embedding_size': 256, 'encoder_dropout': 0.5, 'hidden_size': 256, 'learning_rate': 0.0001, 'num_layers': 1}
config: {'data_path': 'dakshina_dataset_v1.0/hi/lexicons/', 'embedding_size': 256, 'hidden_size': 256, 'num_encoder_layers': 1, 'num_decoder_layers': 1, 'encoder_dropout': 0.5, 'decoder_dropout': 0.5, 'cell_type': 'lstm', 'batch_size': 32, 'learning_rate': 0.0001, 'n_epochs': 20, 'clip': 1.0, 'teacher_forcing_ratio': 0.5, 'patience': 5, 'min_delta': 0.0, 'beam_size': None, 'save_path': 'models/', 'model_name': 'best_model.pt', 'seed': 42, 'log_wandb': True, 'wandb_project': 'da6401_assignment3', 'wandb_name': 'lstm-ec_1-dc_1-hs_256-emb_256-bs_32-lr_0.0001', '_wandb': {}}
2025-05-17 20:26:15,980 INFO    Thread-25 (_run_job):788773 [wandb_init.py:init():786] wandb.init called with sweep_config: {'batch_size': 32, 'beam_size': None, 'cell_type': 'lstm', 'decoder_dropout': 0.5, 'embedding_size': 256, 'encoder_dropout': 0.5, 'hidden_size': 256, 'learning_rate': 0.0001, 'num_layers': 1}
config: {'data_path': 'dakshina_dataset_v1.0/hi/lexicons/', 'embedding_size': 256, 'hidden_size': 256, 'num_encoder_layers': 1, 'num_decoder_layers': 1, 'encoder_dropout': 0.5, 'decoder_dropout': 0.5, 'cell_type': 'lstm', 'batch_size': 32, 'learning_rate': 0.0001, 'n_epochs': 20, 'clip': 1.0, 'teacher_forcing_ratio': 0.5, 'patience': 5, 'min_delta': 0.0, 'beam_size': None, 'save_path': 'models/', 'model_name': 'best_model.pt', 'seed': 42, 'log_wandb': True, 'wandb_project': 'da6401_assignment3', 'wandb_name': 'lstm-ec_1-dc_1-hs_256-emb_256-bs_32-lr_0.0001', '_wandb': {}}
2025-05-17 20:26:15,980 INFO    Thread-25 (_run_job):788773 [wandb_init.py:init():801] wandb.init() called while a run is active
2025-05-17 20:26:15,980 INFO    Thread-25 (_run_job):788773 [wandb_init.py:init():801] wandb.init() called while a run is active
2025-05-17 20:39:41,310 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_finish():2189] finishing run da24s011-indian-institute-of-technology-madras/da6401_assignment3/p9vxcfyy
2025-05-17 20:39:41,310 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_finish():2189] finishing run da24s011-indian-institute-of-technology-madras/da6401_assignment3/p9vxcfyy
2025-05-17 20:39:41,311 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_atexit_cleanup():2419] got exitcode: 0
2025-05-17 20:39:41,311 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_atexit_cleanup():2419] got exitcode: 0
2025-05-17 20:39:41,311 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_restore():2401] restore
2025-05-17 20:39:41,311 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_restore():2401] restore
2025-05-17 20:39:41,311 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_restore():2407] restore done
2025-05-17 20:39:41,311 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_restore():2407] restore done
2025-05-17 20:39:42,900 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_footer_history_summary_info():4064] rendering history
2025-05-17 20:39:42,900 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_footer_history_summary_info():4064] rendering history
2025-05-17 20:39:42,900 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_footer_history_summary_info():4096] rendering summary
2025-05-17 20:39:42,900 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_footer_history_summary_info():4096] rendering summary
2025-05-17 20:39:42,901 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_footer_sync_info():4025] logging synced files
2025-05-17 20:39:42,901 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_footer_sync_info():4025] logging synced files
2025-05-17 20:39:42,909 INFO    Thread-25 (_run_job):788773 [wandb_run.py:_finish():2189] finishing run da24s011-indian-institute-of-technology-madras/da6401_assignment3/p9vxcfyy
2025-05-17 20:39:53,911 INFO    MsgRouterThr:788773 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-05-17 20:56:33,970 INFO    MsgRouterThr:788773 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-05-17 21:13:16,440 INFO    MsgRouterThr:788773 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-05-17 21:24:08,098 INFO    MsgRouterThr:788773 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-05-17 21:24:08,239 ERROR   Thread-34 (_run_job):788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,358 ERROR   Thread-34 (_run_job):788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,472 ERROR   Thread-34 (_run_job):788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,591 ERROR   Thread-34 (_run_job):788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,705 ERROR   Thread-34 (_run_job):788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,815 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,816 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,817 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,818 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,819 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,820 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,821 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,822 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,823 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,824 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,825 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,826 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,826 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,826 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,827 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,827 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,828 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,828 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,829 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,830 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,830 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,831 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,831 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,832 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,832 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,833 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,834 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,834 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,835 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,835 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,836 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,836 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 21:24:08,836 ERROR   MainThread:788773 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
