2025-05-17 16:50:34,447 INFO    MainThread:772685 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-05-17 16:50:34,447 INFO    MainThread:772685 [wandb_setup.py:_flush():67] Configure stats pid to 772685
2025-05-17 16:50:34,447 INFO    MainThread:772685 [wandb_setup.py:_flush():67] Loading settings from /speech/utkarsh/.config/wandb/settings
2025-05-17 16:50:34,447 INFO    MainThread:772685 [wandb_setup.py:_flush():67] Loading settings from /speech/utkarsh/da6401_assignment3/wandb/settings
2025-05-17 16:50:34,447 INFO    MainThread:772685 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-05-17 16:50:34,447 INFO    MainThread:772685 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /speech/utkarsh/da6401_assignment3/wandb/run-20250517_165034-fub6gxkm/logs/debug.log
2025-05-17 16:50:34,447 INFO    MainThread:772685 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /speech/utkarsh/da6401_assignment3/wandb/run-20250517_165034-fub6gxkm/logs/debug-internal.log
2025-05-17 16:50:34,448 INFO    MainThread:772685 [wandb_init.py:init():781] calling init triggers
2025-05-17 16:50:34,448 INFO    MainThread:772685 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'data_path': 'dakshina_dataset_v1.0/hi/lexicons/', 'embedding_size': 64, 'hidden_size': 128, 'num_encoder_layers': 1, 'num_decoder_layers': 1, 'encoder_dropout': 0.3, 'decoder_dropout': 0.3, 'cell_type': 'lstm', 'batch_size': 64, 'learning_rate': 0.001, 'n_epochs': 20, 'clip': 1.0, 'teacher_forcing_ratio': 0.5, 'patience': 5, 'min_delta': 0.0, 'beam_size': None, 'save_path': 'models/', 'model_name': 'best_model.pt', 'seed': 42, 'log_wandb': True, 'wandb_project': 'hindi-transliteration', 'wandb_name': None, '_wandb': {}}
2025-05-17 16:50:34,448 INFO    MainThread:772685 [wandb_init.py:init():809] starting backend
2025-05-17 16:50:34,448 INFO    MainThread:772685 [wandb_init.py:init():813] sending inform_init request
2025-05-17 16:50:34,454 INFO    MainThread:772685 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-17 16:50:34,454 INFO    MainThread:772685 [wandb_init.py:init():823] backend started and connected
2025-05-17 16:50:34,458 INFO    MainThread:772685 [wandb_init.py:init():915] updated telemetry
2025-05-17 16:50:34,466 INFO    MainThread:772685 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-05-17 16:50:35,234 INFO    MainThread:772685 [wandb_init.py:init():1014] starting run threads in backend
2025-05-17 16:50:35,424 INFO    MainThread:772685 [wandb_run.py:_console_start():2454] atexit reg
2025-05-17 16:50:35,424 INFO    MainThread:772685 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-05-17 16:50:35,424 INFO    MainThread:772685 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-05-17 16:50:35,425 INFO    MainThread:772685 [wandb_run.py:_redirect():2394] Redirects installed.
2025-05-17 16:50:35,427 INFO    MainThread:772685 [wandb_init.py:init():1056] run started, returning control to user process
2025-05-17 16:51:40,773 INFO    MsgRouterThr:772685 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-05-17 16:51:41,051 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,054 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,054 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,055 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,055 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,056 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,056 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,057 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,057 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,058 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,058 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,059 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,059 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,060 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,060 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,060 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,061 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,062 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,062 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,062 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,062 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,063 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,063 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,063 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,063 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,063 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,064 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,064 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,064 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,064 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,064 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-17 16:51:41,065 ERROR   MainThread:772685 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/utkarsh/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
